/** Curated registry picks from village postpartum mamas — links stored for export */

export const REGISTRY_CURATED_PRODUCTS = [
  {
    id: 'reg-1',
    title: 'Organic Muslin Swaddle Set (4-Pack)',
    category: 'Nursery · Sleep',
    imageEmoji: '🧸',
    imageTint: 'sage',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e17ddd11?auto=format&fit=crop&w=600&q=80',
    curatedBy: 'Moonlit Nest',
    tip: 'Lightweight muslin was our lifesaver for contact naps and spit-up surprises. Size up!',
    links: {
      amazon: 'https://www.amazon.com/s?k=organic+muslin+swaddle+set',
      target: 'https://www.target.com/s?searchTerm=muslin+swaddle',
      babylist: 'https://www.babylist.com/search?q=muslin+swaddle',
    },
  },
  {
    id: 'reg-2',
    title: 'Hospital-Grade Electric Breast Pump Kit',
    category: 'Feeding · Recovery',
    imageEmoji: '🍼',
    imageTint: 'lavender',
    imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=600&q=80',
    curatedBy: 'Village Willow',
    tip: 'Ask insurance first — many plans cover a pump fully. Extra flange sizes matter more than you think.',
    links: {
      amazon: 'https://www.amazon.com/s?k=hospital+grade+breast+pump',
      target: 'https://www.target.com/s?searchTerm=breast+pump',
      babylist: 'https://www.babylist.com/search?q=breast+pump',
    },
  },
  {
    id: 'reg-3',
    title: 'Blackout Nursery Curtains (Thermal)',
    category: 'Nursery · Sleep',
    imageEmoji: '🌙',
    imageTint: 'lavender',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80',
    curatedBy: 'Sage Bloom Mama',
    tip: 'Total game-changer for naps. Get ones with easy pull — you will use them one-handed constantly.',
    links: {
      amazon: 'https://www.amazon.com/s?k=blackout+nursery+curtains',
      target: 'https://www.target.com/s?searchTerm=blackout+curtains+nursery',
      babylist: 'https://www.babylist.com/search?q=blackout+curtains',
    },
  },
  {
    id: 'reg-4',
    title: 'Postpartum Recovery Care Basket',
    category: 'Mama Care · Wellness',
    imageEmoji: '🌸',
    imageTint: 'sage',
    imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=600&q=80',
    curatedBy: 'Terracotta Heart',
    tip: 'Stock peri bottle, mesh undies, and stool softener before baby arrives. Future-you will be grateful.',
    links: {
      amazon: 'https://www.amazon.com/s?k=postpartum+recovery+kit',
      target: 'https://www.target.com/s?searchTerm=postpartum+care',
      babylist: 'https://www.babylist.com/search?q=postpartum+recovery',
    },
  },
  {
    id: 'reg-5',
    title: 'Sound Machine + Night Light Duo',
    category: 'Nursery · Comfort',
    imageEmoji: '✨',
    imageTint: 'lavender',
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=600&q=80',
    curatedBy: 'Moonlit Nest',
    tip: 'Brown noise > lullabies for us. Pick one with a dim amber light for middle-of-night feeds.',
    links: {
      amazon: 'https://www.amazon.com/s?k=baby+sound+machine+night+light',
      target: 'https://www.target.com/s?searchTerm=sound+machine+baby',
      babylist: 'https://www.babylist.com/search?q=sound+machine',
    },
  },
  {
    id: 'reg-6',
    title: 'Convertible Crib (Greenguard Certified)',
    category: 'Nursery · Furniture',
    imageEmoji: '🛏️',
    imageTint: 'sage',
    imageUrl: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=600&q=80',
    curatedBy: 'Village Willow',
    tip: 'Greenguard low-VOC mattered for our peace of mind. Toddler rail conversion saved money later.',
    links: {
      amazon: 'https://www.amazon.com/s?k=greenguard+convertible+crib',
      target: 'https://www.target.com/s?searchTerm=convertible+crib',
      babylist: 'https://www.babylist.com/search?q=convertible+crib',
    },
  },
  {
    id: 'reg-7',
    title: 'Baby Carrier (Ergonomic Newborn-Ready)',
    category: 'Gear · On the Go',
    imageEmoji: '👶',
    imageTint: 'lavender',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80',
    curatedBy: 'Sage Bloom Mama',
    tip: 'Try in store if you can — fit varies by body. Newborn insert worth every penny early on.',
    links: {
      amazon: 'https://www.amazon.com/s?k=ergonomic+baby+carrier+newborn',
      target: 'https://www.target.com/s?searchTerm=baby+carrier',
      babylist: 'https://www.babylist.com/search?q=baby+carrier',
    },
  },
  {
    id: 'reg-8',
    title: 'Glass Bottle Starter Set + Drying Rack',
    category: 'Feeding · Essentials',
    imageEmoji: '🍶',
    imageTint: 'sage',
    imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=600&q=80',
    curatedBy: 'Terracotta Heart',
    tip: 'We started with two brands before committing. Wide-neck bottles are easier to clean at 3 a.m.',
    links: {
      amazon: 'https://www.amazon.com/s?k=glass+baby+bottle+starter',
      target: 'https://www.target.com/s?searchTerm=glass+baby+bottles',
      babylist: 'https://www.babylist.com/search?q=baby+bottles',
    },
  },
];

export const IMAGE_TINTS = {
  sage: {
    bg: 'rgba(186, 214, 198, 0.65)',
    border: 'rgba(92, 122, 104, 0.35)',
  },
  lavender: {
    bg: 'rgba(210, 190, 225, 0.65)',
    border: 'rgba(139, 116, 168, 0.35)',
  },
};
